version: "3.3"
services:
  app:
   build:
    context: .
    args:
     - DEV=true
   ports:
   - "80:80"
   volumes:
   - ./app:/app
   command: >
    sh -c "python manage.py wait_for_db &&
           python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
  
    environment:
      - DB_HOST =db
      - DB_USER =dev
      - DB_PASSWORD =changeme
      - DB_NAME =devdb
    depends_on:
     - db
  

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: devdb

volumes:
  dev-db-data: